/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.cui.mediaplayer;

import android.app.Service;
import com.tencent.qqmusiccommon.a.e;

import android.content.ComponentName;
import android.content.Context;
import com.tencent.qqmusiccommon.appconfig.g;
import com.tencent.qqmusic.innovation.network.Network;
import android.content.ServiceConnection;
import com.tencent.qqmusic.innovation.common.a.b;
import android.content.Intent;
import android.os.IBinder;
import com.tencent.qqmusic.innovation.common.util.b.d;
import com.tencent.qqmusic.innovation.common.util.b.e;
import android.support.v4.content.c;
import com.tencent.qqmusicplayerprocess.a.a;
import com.tencent.qqmusic.innovation.common.util.g;
import com.tencent.qqmusictv.tinker.TinkerApplicationLike;

import java.util.List;

public class QQPlayerServiceNew extends Service {
    public static boolean a;
    private int b;
    private static Service c;
    private static b d;
    private boolean e;
    private e f;
    private static a g;
    private final b.a h;
    
    public QQPlayerServiceNew() {
        b = -0x1;
        e = false;
        h = new b.a(this) {
            private boolean b;
            
            3(QQPlayerServiceNew p1) {
                b = false;
            }
            
            public synchronized void a(a p1) {
                // :( Parsing error. Please contact me.
            }
            
            public synchronized void b(a p1) {
                b.b("QQPlayerServiceNew", "unRegisterMainProcessInterface");
                try {
                    a().writePlayLog("QQPlayerServiceNew", "unRegisterMainProcessInterface");
                    if(b() != null) {
                        QQPlayerServiceNew.a = 0x0;
                        a(0x0);
                        b = false;
                    }
                } catch(Exception localException1) {
                    b.a("QQPlayerServiceNew", " E : ", localException1);
                }
                QQPlayerServiceNew.a = 0x0;
                a.stopSelf();
            }
            
            public String a() {
                // :( Parsing error. Please contact me.
            }
            
            public int a(String p1, int p2) {
                // :( Parsing error. Please contact me.
            }
            
            public void b() {
                localconst/41 = (VkeyManager)c.getInstance(0x5);
                0x5.networkChanged();
            }
            
            public String c() {
                // :( Parsing error. Please contact me.
            }
            
            public String d() {
                // :( Parsing error. Please contact me.
            }
            
            public String b(String p1, int p2) {
                // :( Parsing error. Please contact me.
            }
            
            public String a(String p1) {
                // :( Parsing error. Please contact me.
            }
            
            public String e() {
                // :( Parsing error. Please contact me.
            }
            
            public String f() {
                // :( Parsing error. Please contact me.
            }
            
            public void g() {
                localconst/41 = (VkeyManager)c.getInstance(0x5);
                0x5.forceToUpdateVkey();
            }
            
            public boolean h() {
                if(a(a) != null) {
                    return a(a).g();
                }
                return false;
            }
            
            public String i() {
                if(a(a) != null) {
                    return a(a).h();
                }
                return null;
            }
            
            public List j() {
                if(a(a) != null) {
                    return a(a).e();
                }
                return null;
            }
            
            public List k() {
                if(a(a) != null) {
                    return a(a).f();
                }
                return null;
            }
            
            public List l() {
                if(a(a) != null) {
                    return a(a).d();
                }
                return null;
            }
            
            public boolean b(String p1) {
                if(a(a) != null) {
                    return a(a).b(p1, true);
                }
                return false;
            }
            
            public String m() {
                if(a(a) != null) {
                    return a(a).b();
                }
                return null;
            }
            
            public String n() {
                if(a(a) != null) {
                    return a(a).c();
                }
                return null;
            }
            
            public String o() {
                if(a(a) != null) {
                    return a(a).i();
                }
                return null;
            }
            
            public String p() {
                if(a(a) != null) {
                    return a(a).j();
                }
                return null;
            }
            
            public String a(int p1) {
                if(a(a) != null) {
                    return a(a).a(p1);
                }
                return null;
            }
            
            public String a(String p1, boolean p2) {
                if(a(a) != null) {
                    return a(a).a(p1, p2);
                }
                return null;
            }
            
            public long q() {
                // :( Parsing error. Please contact me.
            }
            
            public void a(long p1) {
                c localc1 = 0xe;
                (a)c.getInstance(localc1).a(p1);
            }
            
            public void r() {
                c localc1 = 0xe;
                (a)c.getInstance(localc1).c();
            }
            
            public void b(String p1, boolean p2) {
                if(p1 == null) {
                    return;
                }
                try {
                    StringBuffer localStringBuffer1 = new StringBuffer(p1);
                    c localc2 = 0xe;
                    (a)c.getInstance(localc2).a(localStringBuffer1, p2);
                    return;
                } catch(Exception localException3) {
                    b.a("QQPlayerServiceNew", " E : ", localException3);
                }
            }
            
            public void c(String p1) {
                if(p1 == null) {
                    return;
                }
                int localconst/161 = 0xe;
                try {
                    (a)c.getInstance(localc2).a(p1);
                    return;
                } catch(Exception localconst/161) {
                    b.a("QQPlayerServiceNew", " E : ", localconst/161);
                }
            }
            
            public void b(int p1) {
            }
            
            public void c(int p1) {
            }
            
            public void s() {
            }
            
            public String t() {
                return null;
            }
            
            public int u() {
                return 0x0;
            }
            
            public String a(boolean p1) {
                return null;
            }
            
            public void d(String p1) {
            }
            
            public String v() {
                try {
                    return a().getWeakQQ();
                } catch(Exception localException1) {
                    b.a("QQPlayerServiceNew", " E : ", localException1);
                }
                return "";
            }
            
            public boolean w() {
                return f.h();
            }
            
            public void e(String p1) {
                try {
                    CrashReport.setUserId(c(), p1);
                    localService1 = (VkeyManager)c.getInstance(0x5);
                    0x5.onLoginStateChanged(p1);
                    return;
                } catch(Exception localException2) {
                    b.a("QQPlayerServiceNew", localException2);
                }
            }
            
            public String x() {
                // :( Parsing error. Please contact me.
            }
            
            public void a(int p1, int p2, float p3) {
                k.a(p1, p2, p3);
            }
        };
    }
    
    public static a a() {
        if(g != null) {
            return g;
            return g;
        }
        throw new Exception("Interface not registered");
    }
    
    public void onCreate() {
        super.onCreate();
        b.b("QQPlayerServiceNew", "onCreate");
        c = this;
        d = h;
        a(this);
        d.a().a(new e.a(this) {
            
            1(QQPlayerServiceNew p1) {
            }
            
            public Void b(e.b p1) {
                a(a, d.a());
                return null;
            }
        });
        c.getInstance(0x11);
        c.a(getApplicationContext());
        a.a();
    }
    
    public static synchronized void a(Context p1) {
        if(!g.k) {
            try {
                Network.a().d();
                c.programmeStart(p1);
                d.a(p1, new ServiceConnection() {
                    
                    public void onServiceConnected(ComponentName p1, IBinder p2) {
                        // :( Parsing error. Please contact me.
                    }
                    
                    public void onServiceDisconnected(ComponentName p1) {
                    }
                });
                e.a();
            } catch(Exception localException1) {
                b.a("appStart programStartForPlayerProcess", localException1);
            }
        }
        g.k = 0x1;
    }
}

public void onDestroy() {
    try {
        a = 0x0;
        c.a(getApplicationContext());
        if(f != null) {
            f.a();
        }
    } catch(Exception localException1) {
        b.a("QQPlayerServiceNew", localException1);
    }
    super.onDestroy();
    try {
        System.exit(0x0);
        return;
    } catch(Exception localException2) {
        b.a("QQPlayerServiceNew", " E : ", localException2);
    }
}

public IBinder onBind(Intent p1) {
    b.b("QQPlayerServiceNew", "onBind: " + p1.getAction());
    return h;
}

public void onRebind(Intent p1) {
}

public boolean onUnbind(Intent p1) {
    stopSelf(b);
    return true;
}

public void onLowMemory() {
    b.d("QQPlayerServiceNew", "onLowMemory");
    try {
        g.a().a(c);
        b.c();
        a().writePlayLog("QQPlayerServiceNew", "onLowMemory");
    } catch(Exception localException1) {
        b.a("QQPlayerServiceNew", " E : ", localException1);
    }
    super.onLowMemory();
}

public void onTrimMemory(int p1) {
    b.d("QQPlayerServiceNew", "onTrimMemory level : " + p1);
    try {
        b.c();
        a().writePlayLog("QQPlayerServiceNew", "onTrimMemory level : " + p1);
    } catch(Exception localException1) {
        b.a("QQPlayerServiceNew", " E : ", localException1);
    }
    super.onTrimMemory(p1);
}

public void onTaskRemoved(Intent p1) {
    b.d("QQPlayerServiceNew", "onTaskRemoved");
    TinkerApplicationLike.ExitApplication();
    super.onTaskRemoved(p1);
}

public int onStartCommand(Intent p1, int p2, int p3) {
    b = p3;
    return 0x1;
}
}
